# GitHub Labels Configuration for main-nicholas
# Comprehensive label structure for GitHub-Bugbot automation

labels:
  # Priority Levels
  - name: "priority: critical"
    color: "d73a4a"
    description: "Issues that block development or production"
  - name: "priority: high"
    color: "f85149"
    description: "Important issues that should be addressed soon"
  - name: "priority: medium"
    color: "fbca04"
    description: "Issues that can be addressed in normal workflow"
  - name: "priority: low"
    color: "0e8a16"
    description: "Nice-to-have improvements"

  # Issue Types
  - name: "type: bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "type: feature"
    color: "a2eeef"
    description: "New feature or request"
  - name: "type: enhancement"
    color: "7057ff"
    description: "Improvement to existing feature"
  - name: "type: documentation"
    color: "008672"
    description: "Documentation improvements"
  - name: "type: refactor"
    color: "ff6b6b"
    description: "Code refactoring without changing functionality"

  # Component Areas
  - name: "component: hero"
    color: "1d76db"
    description: "Hero section component"
  - name: "component: pricing"
    color: "1d76db"
    description: "Pricing section component"
  - name: "component: offers"
    color: "1d76db"
    description: "Offers stack component"
  - name: "component: compliance"
    color: "1d76db"
    description: "Compliance-related components"
  - name: "component: landing"
    color: "1d76db"
    description: "Landing page components"
  - name: "component: navbar"
    color: "1d76db"
    description: "Navigation component"
  - name: "component: footer"
    color: "1d76db"
    description: "Footer component"

  # Automation Labels
  - name: "bugbot: auto-assign"
    color: "6f42c1"
    description: "Auto-assign to Bugbot for analysis"
  - name: "bugbot: auto-fix"
    color: "6f42c1"
    description: "Bugbot can automatically fix this"
  - name: "bugbot: review-only"
    color: "6f42c1"
    description: "Bugbot should review but not auto-fix"

  # Status Labels
  - name: "status: needs-triage"
    color: "f9d0c4"
    description: "Issue needs initial triage"
  - name: "status: in-progress"
    color: "f9d0c4"
    description: "Issue is being worked on"
  - name: "status: blocked"
    color: "f9d0c4"
    description: "Issue is blocked by external factors"
  - name: "status: ready-for-review"
    color: "f9d0c4"
    description: "Issue is ready for review"
  - name: "status: completed"
    color: "f9d0c4"
    description: "Issue has been completed"

  # ASIC Compliance Specific
  - name: "domain: asic-compliance"
    color: "0366d6"
    description: "ASIC compliance related"
  - name: "domain: landing-page"
    color: "0366d6"
    description: "Landing page related"
  - name: "domain: offers-meta-agent"
    color: "0366d6"
    description: "Offers meta-agent workflow"
